export const books = [
  {
    title: "A revolução dos bichos",
    author: "George Orwell",
    imageUrl: "/books/a-revolucao-dos-bichos.png",
    rating: 4,
    read: false,
    category: "Política Literatura, Ficção",
    pages: 96,
    ratingCount: 15,
  },
  {
    title: "14 Hábitos de desenvolvedores altamente produtivos",
    author: "Zeno Rocha",
    imageUrl: "/books/14-habitos-de-desenvolvedores-altamente-produtivos.png",
    rating: 4,
    read: false,
    category: "Computação, Programação",
    pages: 160,
    ratingCount: 15,
  },
  {
    title: "O fim da eternidade",
    author: "Isaac Asimov",
    imageUrl: "/books/o-fim-da-eternidade.png",
    rating: 4,
    read: false,
    category: "Ficção, Romance",
    pages: 256,
    ratingCount: 15,
  },
  {
    title: "Entendendo Algoritmos",
    author: "Aditya Y. Bhargava",
    imageUrl: "/books/entendendo-algoritmos.png",
    rating: 4,
    read: false,
    category: "Obra de referência",
    pages: 264,
    ratingCount: 15,
  },
  {
    title: "Código limpo",
    author: "Robert C. Martin",
    imageUrl: "/books/codigo-limpo.png",
    rating: 4,
    read: false,
    category: "Computação, Programação",
    pages: 456,
    ratingCount: 15,
  },
  {
    title: "O poder do hábito",
    author: "Charles Duhigg",
    imageUrl: "/books/o-poder-do-habito.png",
    rating: 4,
    read: false,
    category: "Autoajuda",
    pages: 408,
    ratingCount: 15,
  },
  {
    title: "Arquitetura limpa",
    author: "Robert C. Martin",
    imageUrl: "/books/arquitetura-limpa.png",
    rating: 4,
    read: false,
    category: "Obra de referência",
    pages: 432,
    ratingCount: 15,
  },
  {
    title: "O Hobbit",
    author: "J.R.R. Tolkien",
    imageUrl: "/books/o-hobbit.png",
    rating: 4,
    read: false,
    category: "Fantasia, Ficção",
    pages: 336,
    ratingCount: 15,
  },
  {
    title: "Histórias extraordinárias",
    author: "Edgar Allan Poe",
    imageUrl: "/books/historias-extraordinarias.png",
    rating: 4,
    read: false,
    category: "Ficção",
    pages: 272,
    ratingCount: 15,
  },
  {
    title: "Refatoração",
    author: "Martin Fowler",
    imageUrl: "/books/refatoracao.png",
    rating: 4,
    read: false,
    category: "Obra de referência",
    pages: 456,
    ratingCount: 15,
  },
  {
    title: "Domain-Driven Design",
    author: "Eric Evans",
    imageUrl: "/books/domain-driven-design.png",
    rating: 4,
    read: false,
    category: "Computação, Programação",
    pages: 529,
    ratingCount: 15,
  },
  {
    title: "Viagem ao Centro da Terra",
    author: "Julio Verne",
    imageUrl: "/books/viagem-ao-centro-da-terra.png",
    rating: 4,
    read: false,
    category: "Ficção, Aventura",
    pages: 256,
    ratingCount: 15,
  },
  {
    title: "O guia do mochileiro das galáxias",
    author: "Douglas Adams",
    imageUrl: "/books/o-guia-do-mochileiro-das-galaxias.png",
    rating: 4,
    read: false,
    category: "Ficção",
    pages: 208,
    ratingCount: 15,
  },
  {
    title: "Fragmentos do Horror",
    author: "Junji Ito",
    imageUrl: "/books/fragmentos-do-horror.png",
    rating: 4,
    read: false,
    category: "Quadrinhos",
    pages: 224,
    ratingCount: 15,
  },
  {
    title: "O Programador Pragmático",
    author: "Andrew Hunt",
    imageUrl: "/books/o-programador-pragmatico.png",
    rating: 4,
    read: false,
    category: "Computação, Programação",
    pages: 344,
    ratingCount: 15,
  },
]
